-- Gestão de contratos (admin)
-- Data: 2026-03-02

begin;

create table if not exists public.contratos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  titulo text not null,
  cliente_nome text not null,
  cliente_email text,
  cliente_telefone text,
  status text not null default 'rascunho',
  valor_total numeric(12,2),
  data_inicio date,
  data_fim date,
  data_assinatura date,
  descricao text,
  observacoes text,
  proposta_id bigint references public.proposta(id) on delete set null,

  -- Campos do documento contratual
  cliente_endereco text,
  cliente_cep text,
  cliente_cnpj text,
  prazo_dias integer,
  prazo_garantia_dias integer,
  condicoes_pagamento text,
  valor_hora_suporte numeric(12,2),
  multa_absorcao text default '100.000,00',
  percentual_resilicao text default '80%',
  email_suporte text,
  canal_atendimento text,
  banco_nome text,
  banco_agencia text,
  banco_conta text,
  chave_pix text,
  cidade_foro text default 'Imperatriz',
  estado_foro text default 'Maranhão',

  constraint contratos_status_check check (status in ('rascunho', 'enviado', 'assinado', 'encerrado', 'cancelado')),
  constraint contratos_valor_total_check check (valor_total is null or valor_total >= 0)
);

create index if not exists contratos_status_idx
  on public.contratos(status);

create index if not exists contratos_cliente_nome_idx
  on public.contratos(lower(cliente_nome));

create index if not exists contratos_proposta_id_idx
  on public.contratos(proposta_id);

create or replace function public.contratos_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_contratos_updated_at on public.contratos;
create trigger trg_contratos_updated_at
before update on public.contratos
for each row
execute function public.contratos_set_updated_at();

alter table public.contratos enable row level security;

drop policy if exists "contratos_auth_all" on public.contratos;
create policy "contratos_auth_all"
  on public.contratos
  for all
  to authenticated
  using (true)
  with check (true);

comment on table public.contratos is 'Gestão de contratos comerciais no painel admin';
comment on column public.contratos.status is 'Etapa do contrato no processo comercial';

commit;