-- CRM completo de clientes (admin)
-- Data: 2026-02-25

begin;

create table if not exists public.crm_clientes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nome text not null,
  empresa text,
  email text,
  telefone text,
  origem text not null default 'site',
  status text not null default 'lead',
  prioridade text not null default 'media',
  valor_potencial numeric(12,2),
  proximo_followup date,
  responsavel text,
  tags text[] default '{}',
  observacoes text,
  ultima_interacao_em timestamptz,
  proposta_id bigint references public.proposta(id) on delete set null,
  constraint crm_clientes_status_check check (status in ('lead', 'contato_inicial', 'proposta_enviada', 'negociacao', 'fechado_ganho', 'fechado_perdido')),
  constraint crm_clientes_prioridade_check check (prioridade in ('baixa', 'media', 'alta')),
  constraint crm_clientes_valor_potencial_check check (valor_potencial is null or valor_potencial >= 0)
);

create table if not exists public.crm_interacoes (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.crm_clientes(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  tipo text not null default 'nota',
  resumo text not null,
  detalhes text,
  data_interacao timestamptz not null default now(),
  proxima_acao date,
  valor_mencionado numeric(12,2),
  constraint crm_interacoes_tipo_check check (tipo in ('ligacao', 'whatsapp', 'email', 'reuniao', 'proposta', 'nota')),
  constraint crm_interacoes_valor_mencionado_check check (valor_mencionado is null or valor_mencionado >= 0)
);

create index if not exists crm_clientes_status_idx
  on public.crm_clientes(status);

create index if not exists crm_clientes_followup_idx
  on public.crm_clientes(proximo_followup);

create index if not exists crm_clientes_proposta_id_idx
  on public.crm_clientes(proposta_id);

create index if not exists crm_clientes_email_idx
  on public.crm_clientes(lower(email));

create index if not exists crm_interacoes_cliente_data_idx
  on public.crm_interacoes(cliente_id, data_interacao desc);

create or replace function public.crm_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.crm_sync_ultima_interacao()
returns trigger
language plpgsql
as $$
declare
  target_cliente_id bigint;
begin
  target_cliente_id := coalesce(new.cliente_id, old.cliente_id);

  update public.crm_clientes c
  set ultima_interacao_em = (
    select max(i.data_interacao)
    from public.crm_interacoes i
    where i.cliente_id = target_cliente_id
  )
  where c.id = target_cliente_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_crm_clientes_updated_at on public.crm_clientes;
create trigger trg_crm_clientes_updated_at
before update on public.crm_clientes
for each row
execute function public.crm_set_updated_at();

drop trigger if exists trg_crm_interacoes_updated_at on public.crm_interacoes;
create trigger trg_crm_interacoes_updated_at
before update on public.crm_interacoes
for each row
execute function public.crm_set_updated_at();

drop trigger if exists trg_crm_interacoes_sync_ultima_interacao_ins on public.crm_interacoes;
create trigger trg_crm_interacoes_sync_ultima_interacao_ins
after insert on public.crm_interacoes
for each row
execute function public.crm_sync_ultima_interacao();

drop trigger if exists trg_crm_interacoes_sync_ultima_interacao_upd on public.crm_interacoes;
create trigger trg_crm_interacoes_sync_ultima_interacao_upd
after update of data_interacao on public.crm_interacoes
for each row
execute function public.crm_sync_ultima_interacao();

drop trigger if exists trg_crm_interacoes_sync_ultima_interacao_del on public.crm_interacoes;
create trigger trg_crm_interacoes_sync_ultima_interacao_del
after delete on public.crm_interacoes
for each row
execute function public.crm_sync_ultima_interacao();

alter table public.crm_clientes enable row level security;
alter table public.crm_interacoes enable row level security;

drop policy if exists "crm_clientes_auth_all" on public.crm_clientes;
create policy "crm_clientes_auth_all"
  on public.crm_clientes
  for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "crm_interacoes_auth_all" on public.crm_interacoes;
create policy "crm_interacoes_auth_all"
  on public.crm_interacoes
  for all
  to authenticated
  using (true)
  with check (true);

comment on table public.crm_clientes is 'CRM de clientes e oportunidades comerciais';
comment on table public.crm_interacoes is 'Histórico de interações de cada cliente no CRM';

comment on column public.crm_clientes.status is 'Etapa atual no funil comercial';
comment on column public.crm_clientes.proximo_followup is 'Data prevista para próximo contato';
comment on column public.crm_clientes.valor_potencial is 'Valor potencial estimado da oportunidade';
comment on column public.crm_clientes.ultima_interacao_em is 'Data/hora da última interação registrada';

comment on column public.crm_interacoes.tipo is 'Canal/tipo da interação com o cliente';
comment on column public.crm_interacoes.proxima_acao is 'Próximo passo sugerido após a interação';

commit;
